import { db } from "../db";
import { courses, games, placementTestQuestions } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedSampleCourses() {
  const existingCourses = await db.select({ count: sql<number>`count(*)` }).from(courses);
  if (Number(existingCourses[0]?.count) > 0) {
    console.log("✅ Courses already seeded, skipping.");
    return;
  }

  const sampleCourses = [
    {
      title: "English for Beginners (A1)",
      description: "A comprehensive foundation course in English covering basic grammar, essential vocabulary, and everyday conversation skills. Perfect for absolute beginners.",
      language: "English",
      level: "A1",
      price: 2500000,
      isActive: true,
      duration: 45,
      totalLessons: 24,
      totalSessions: 24,
      sessionDuration: 60,
      category: "General English",
      difficulty: "beginner",
      isFeatured: true,
      deliveryMode: "hybrid",
      targetLanguage: "English",
      proficiencyLevel: "A1",
      classFormat: "group",
      maxStudents: 15,
      targetLevel: "A2",
      courseCode: "ENG-A1-001",
      tags: ["beginner", "general", "foundation"],
      learningObjectives: ["Basic grammar structures", "Essential vocabulary (500 words)", "Simple conversations", "Reading short texts"],
    },
    {
      title: "English Intermediate (B1)",
      description: "Build fluency and confidence with intermediate English skills. Focus on complex grammar, expanded vocabulary, and real-world communication scenarios.",
      language: "English",
      level: "B1",
      price: 3500000,
      isActive: true,
      duration: 45,
      totalLessons: 30,
      totalSessions: 30,
      sessionDuration: 75,
      category: "General English",
      difficulty: "intermediate",
      isFeatured: true,
      deliveryMode: "hybrid",
      targetLanguage: "English",
      proficiencyLevel: "B1",
      classFormat: "group",
      maxStudents: 12,
      targetLevel: "B2",
      courseCode: "ENG-B1-001",
      tags: ["intermediate", "general", "fluency"],
      learningObjectives: ["Complex grammar (conditionals, passives)", "Expanded vocabulary (2000 words)", "Discussion and debate skills", "Academic writing basics"],
    },
    {
      title: "IELTS Preparation Course",
      description: "Intensive IELTS preparation covering all four skills: Listening, Reading, Writing, and Speaking. Includes mock tests, strategies, and personalized feedback.",
      language: "English",
      level: "B2",
      price: 5000000,
      isActive: true,
      duration: 60,
      totalLessons: 36,
      totalSessions: 36,
      sessionDuration: 90,
      category: "Exam Preparation",
      difficulty: "advanced",
      isFeatured: true,
      deliveryMode: "online",
      targetLanguage: "English",
      proficiencyLevel: "B2",
      classFormat: "group",
      maxStudents: 10,
      targetLevel: "C1",
      courseCode: "IELTS-001",
      tags: ["ielts", "exam", "academic", "preparation"],
      learningObjectives: ["IELTS Listening strategies", "Academic Reading techniques", "Task 1 & Task 2 Writing", "Speaking test preparation"],
    },
    {
      title: "Business English",
      description: "Professional English for the workplace. Learn business vocabulary, email writing, presentation skills, negotiation language, and meeting protocols.",
      language: "English",
      level: "B2",
      price: 4500000,
      isActive: true,
      duration: 45,
      totalLessons: 20,
      totalSessions: 20,
      sessionDuration: 60,
      category: "Business English",
      difficulty: "intermediate",
      isFeatured: false,
      deliveryMode: "online",
      targetLanguage: "English",
      proficiencyLevel: "B2",
      classFormat: "group",
      maxStudents: 8,
      targetLevel: "C1",
      courseCode: "BUS-ENG-001",
      tags: ["business", "professional", "workplace"],
      learningObjectives: ["Business email writing", "Presentation skills", "Meeting vocabulary", "Negotiation language"],
    },
    {
      title: "English for Kids (7-12)",
      description: "Fun and interactive English learning for children aged 7-12. Uses games, songs, stories, and creative activities to build language skills naturally.",
      language: "English",
      level: "A1",
      price: 2000000,
      isActive: true,
      duration: 30,
      totalLessons: 24,
      totalSessions: 24,
      sessionDuration: 45,
      category: "Kids English",
      difficulty: "beginner",
      isFeatured: true,
      deliveryMode: "hybrid",
      targetLanguage: "English",
      proficiencyLevel: "A1",
      classFormat: "group",
      maxStudents: 10,
      targetLevel: "A2",
      courseCode: "KIDS-ENG-001",
      tags: ["kids", "children", "fun", "interactive"],
      learningObjectives: ["Basic vocabulary through games", "Simple sentence structures", "Phonics and pronunciation", "Listening comprehension"],
    },
    {
      title: "Conversation Club",
      description: "Weekly conversation practice sessions with native speakers. Focus on fluency, pronunciation, and natural expression. Open to all levels.",
      language: "English",
      level: "B1",
      price: 1500000,
      isActive: true,
      duration: 60,
      totalLessons: 12,
      totalSessions: 12,
      sessionDuration: 60,
      category: "Conversation",
      difficulty: "intermediate",
      isFeatured: false,
      deliveryMode: "online",
      targetLanguage: "English",
      proficiencyLevel: "B1",
      classFormat: "group",
      maxStudents: 6,
      targetLevel: "B2",
      courseCode: "CONV-001",
      tags: ["conversation", "speaking", "fluency", "native"],
      learningObjectives: ["Improve fluency", "Natural expressions", "Pronunciation practice", "Cultural awareness"],
    },
    {
      title: "Arabic for Persian Speakers",
      description: "Learn Arabic using your Persian language background as an advantage. Covers shared vocabulary, grammar differences, and practical communication.",
      language: "Arabic",
      level: "A1",
      price: 3000000,
      isActive: true,
      duration: 45,
      totalLessons: 20,
      totalSessions: 20,
      sessionDuration: 60,
      category: "Arabic",
      difficulty: "beginner",
      isFeatured: false,
      deliveryMode: "hybrid",
      targetLanguage: "Arabic",
      proficiencyLevel: "A1",
      classFormat: "group",
      maxStudents: 12,
      targetLevel: "A2",
      courseCode: "ARA-FA-001",
      tags: ["arabic", "persian-speakers", "beginner"],
      learningObjectives: ["Arabic alphabet mastery", "Shared Persian-Arabic vocabulary", "Basic conversation", "Reading Arabic texts"],
    },
    {
      title: "Advanced English (C1)",
      description: "Master advanced English with focus on academic writing, complex argumentation, nuanced vocabulary, and professional presentation skills.",
      language: "English",
      level: "C1",
      price: 5500000,
      isActive: true,
      duration: 60,
      totalLessons: 24,
      totalSessions: 24,
      sessionDuration: 90,
      category: "General English",
      difficulty: "advanced",
      isFeatured: false,
      deliveryMode: "online",
      targetLanguage: "English",
      proficiencyLevel: "C1",
      classFormat: "group",
      maxStudents: 8,
      targetLevel: "C2",
      courseCode: "ENG-C1-001",
      tags: ["advanced", "academic", "professional"],
      learningObjectives: ["Academic essay writing", "Complex grammar mastery", "Professional vocabulary (5000+ words)", "Critical thinking in English"],
    },
  ];

  for (const course of sampleCourses) {
    await db.insert(courses).values(course);
  }
  console.log(`✅ Seeded ${sampleCourses.length} sample courses.`);
}

export async function seedSampleGames() {
  const existingGames = await db.select({ count: sql<number>`count(*)` }).from(games);
  if (Number(existingGames[0]?.count) > 0) {
    console.log("✅ Games already seeded, skipping.");
    return;
  }

  const sampleGames = [
    {
      title: "Vocabulary Builder",
      description: "Match English words with their Persian translations. Earn points for speed and accuracy!",
      gameType: "vocabulary",
      category: "vocabulary",
      difficulty: "easy",
      language: "en",
      estimatedDuration: 10,
      maxScore: 100,
      passScore: 60,
      instructions: "Match each English word with its correct Persian translation. You have 60 seconds per round.",
      isActive: true,
      isPublic: true,
      tags: ["vocabulary", "translation", "beginner"],
      skillsTargeted: ["vocabulary", "reading"],
      xpReward: 15,
      coinReward: 5,
    },
    {
      title: "Grammar Challenge",
      description: "Test your grammar skills with fill-in-the-blank and sentence correction questions.",
      gameType: "grammar",
      category: "grammar",
      difficulty: "medium",
      language: "en",
      estimatedDuration: 15,
      maxScore: 100,
      passScore: 70,
      instructions: "Choose the correct grammar option for each question. Some questions have multiple parts.",
      isActive: true,
      isPublic: true,
      tags: ["grammar", "sentence-structure", "intermediate"],
      skillsTargeted: ["grammar", "writing"],
      xpReward: 20,
      coinReward: 8,
    },
    {
      title: "Listening Quiz",
      description: "Listen to audio clips and answer comprehension questions to improve your listening skills.",
      gameType: "quiz",
      category: "listening",
      difficulty: "medium",
      language: "en",
      estimatedDuration: 20,
      maxScore: 100,
      passScore: 65,
      instructions: "Listen carefully to each audio clip and answer the questions that follow.",
      isActive: true,
      isPublic: true,
      tags: ["listening", "comprehension", "audio"],
      skillsTargeted: ["listening", "comprehension"],
      xpReward: 25,
      coinReward: 10,
    },
    {
      title: "Word Scramble",
      description: "Unscramble letters to form correct English words. Race against the clock!",
      gameType: "vocabulary",
      category: "spelling",
      difficulty: "easy",
      language: "en",
      estimatedDuration: 10,
      maxScore: 100,
      passScore: 50,
      instructions: "Rearrange the scrambled letters to form the correct English word. Hints are available!",
      isActive: true,
      isPublic: true,
      tags: ["spelling", "vocabulary", "fun"],
      skillsTargeted: ["vocabulary", "spelling"],
      xpReward: 10,
      coinReward: 3,
    },
    {
      title: "Sentence Builder",
      description: "Put words in the correct order to form grammatically correct sentences.",
      gameType: "grammar",
      category: "sentence-structure",
      difficulty: "medium",
      language: "en",
      estimatedDuration: 15,
      maxScore: 100,
      passScore: 70,
      instructions: "Drag and drop the words into the correct order to build proper English sentences.",
      isActive: true,
      isPublic: true,
      tags: ["grammar", "word-order", "intermediate"],
      skillsTargeted: ["grammar", "writing", "syntax"],
      xpReward: 20,
      coinReward: 7,
    },
    {
      title: "Story Adventure",
      description: "Read an interactive story and make choices that test your English comprehension and vocabulary.",
      gameType: "story",
      category: "reading",
      difficulty: "hard",
      language: "en",
      estimatedDuration: 25,
      maxScore: 150,
      passScore: 90,
      instructions: "Read each part of the story carefully and choose the best response. Your choices affect the outcome!",
      isActive: true,
      isPublic: true,
      tags: ["reading", "story", "comprehension", "advanced"],
      skillsTargeted: ["reading", "vocabulary", "comprehension"],
      xpReward: 35,
      coinReward: 15,
    },
  ];

  for (const game of sampleGames) {
    await db.insert(games).values(game);
  }
  console.log(`✅ Seeded ${sampleGames.length} sample games.`);
}

export async function seedPlacementTestQuestions() {
  const existingQuestions = await db.select({ count: sql<number>`count(*)` }).from(placementTestQuestions);
  if (Number(existingQuestions[0]?.count) > 0) {
    console.log("✅ Placement test questions already seeded, skipping.");
    return;
  }

  const questions = [
    {
      skill: "grammar",
      cefrLevel: "A1",
      questionType: "multiple_choice",
      title: "Present Simple - To Be",
      prompt: "Choose the correct form of 'to be'.",
      content: {
        question: "She ___ a teacher.",
        options: ["am", "is", "are", "be"],
        correctAnswer: "is"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 30,
      scoringCriteria: { correctAnswer: "is", points: 10 },
      maxScore: 10,
      difficultyWeight: "0.20",
      tags: ["grammar", "present-simple", "to-be"],
      isActive: true,
    },
    {
      skill: "grammar",
      cefrLevel: "A1",
      questionType: "multiple_choice",
      title: "Articles - A/An",
      prompt: "Choose the correct article.",
      content: {
        question: "I have ___ umbrella.",
        options: ["a", "an", "the", "—"],
        correctAnswer: "an"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 30,
      scoringCriteria: { correctAnswer: "an", points: 10 },
      maxScore: 10,
      difficultyWeight: "0.20",
      tags: ["grammar", "articles"],
      isActive: true,
    },
    {
      skill: "vocabulary",
      cefrLevel: "A1",
      questionType: "multiple_choice",
      title: "Basic Colors",
      prompt: "Choose the correct word.",
      content: {
        question: "The sky is ___.",
        options: ["red", "green", "blue", "yellow"],
        correctAnswer: "blue"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 20,
      scoringCriteria: { correctAnswer: "blue", points: 10 },
      maxScore: 10,
      difficultyWeight: "0.15",
      tags: ["vocabulary", "colors", "basic"],
      isActive: true,
    },
    {
      skill: "grammar",
      cefrLevel: "A2",
      questionType: "multiple_choice",
      title: "Past Simple - Regular Verbs",
      prompt: "Choose the correct past tense.",
      content: {
        question: "Yesterday, I ___ to school.",
        options: ["walk", "walked", "walking", "walks"],
        correctAnswer: "walked"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 30,
      scoringCriteria: { correctAnswer: "walked", points: 15 },
      maxScore: 15,
      difficultyWeight: "0.30",
      tags: ["grammar", "past-simple", "regular-verbs"],
      isActive: true,
    },
    {
      skill: "grammar",
      cefrLevel: "A2",
      questionType: "multiple_choice",
      title: "Comparatives",
      prompt: "Choose the correct comparative form.",
      content: {
        question: "A car is ___ than a bicycle.",
        options: ["fast", "faster", "fastest", "more fast"],
        correctAnswer: "faster"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 30,
      scoringCriteria: { correctAnswer: "faster", points: 15 },
      maxScore: 15,
      difficultyWeight: "0.30",
      tags: ["grammar", "comparatives"],
      isActive: true,
    },
    {
      skill: "reading",
      cefrLevel: "B1",
      questionType: "multiple_choice",
      title: "Reading Comprehension - Main Idea",
      prompt: "Read the text and answer the question.",
      content: {
        passage: "Learning a new language opens many doors. It allows you to communicate with people from different cultures, enhances your career prospects, and even improves your cognitive abilities. Studies show that bilingual people have better problem-solving skills.",
        question: "What is the main idea of this passage?",
        options: [
          "Language learning is difficult",
          "Learning a new language has multiple benefits",
          "Bilingual people are smarter",
          "Career prospects are important"
        ],
        correctAnswer: "Learning a new language has multiple benefits"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 90,
      scoringCriteria: { correctAnswer: "Learning a new language has multiple benefits", points: 20 },
      maxScore: 20,
      difficultyWeight: "0.50",
      tags: ["reading", "comprehension", "main-idea"],
      isActive: true,
    },
    {
      skill: "grammar",
      cefrLevel: "B1",
      questionType: "multiple_choice",
      title: "Present Perfect vs Past Simple",
      prompt: "Choose the correct tense.",
      content: {
        question: "I ___ in Tehran since 2020.",
        options: ["live", "lived", "have lived", "am living"],
        correctAnswer: "have lived"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 45,
      scoringCriteria: { correctAnswer: "have lived", points: 20 },
      maxScore: 20,
      difficultyWeight: "0.50",
      tags: ["grammar", "present-perfect", "past-simple"],
      isActive: true,
    },
    {
      skill: "vocabulary",
      cefrLevel: "B1",
      questionType: "multiple_choice",
      title: "Academic Vocabulary",
      prompt: "Choose the word that best completes the sentence.",
      content: {
        question: "The scientist ___ the experiment three times to confirm the results.",
        options: ["made", "conducted", "did", "performed"],
        correctAnswer: "conducted"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 45,
      scoringCriteria: { correctAnswer: "conducted", points: 20 },
      maxScore: 20,
      difficultyWeight: "0.50",
      tags: ["vocabulary", "academic"],
      isActive: true,
    },
    {
      skill: "grammar",
      cefrLevel: "B2",
      questionType: "multiple_choice",
      title: "Conditional Sentences - Type 2",
      prompt: "Choose the correct form.",
      content: {
        question: "If I ___ more money, I would travel the world.",
        options: ["have", "had", "would have", "having"],
        correctAnswer: "had"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 45,
      scoringCriteria: { correctAnswer: "had", points: 25 },
      maxScore: 25,
      difficultyWeight: "0.65",
      tags: ["grammar", "conditionals", "type-2"],
      isActive: true,
    },
    {
      skill: "grammar",
      cefrLevel: "B2",
      questionType: "multiple_choice",
      title: "Passive Voice",
      prompt: "Transform to passive voice.",
      content: {
        question: "Which is the correct passive form of 'They built this bridge in 1990'?",
        options: [
          "This bridge built in 1990",
          "This bridge was built in 1990",
          "This bridge is built in 1990",
          "This bridge has been built in 1990"
        ],
        correctAnswer: "This bridge was built in 1990"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 60,
      scoringCriteria: { correctAnswer: "This bridge was built in 1990", points: 25 },
      maxScore: 25,
      difficultyWeight: "0.65",
      tags: ["grammar", "passive-voice"],
      isActive: true,
    },
    {
      skill: "reading",
      cefrLevel: "C1",
      questionType: "multiple_choice",
      title: "Inference and Implication",
      prompt: "Read the text and infer the author's position.",
      content: {
        passage: "While technology has undoubtedly transformed education, making information more accessible than ever before, one cannot help but wonder whether the depth of understanding has kept pace with the breadth of available knowledge. The ease with which students can now access answers may paradoxically diminish the very cognitive processes that deep learning requires.",
        question: "What does the author imply about technology in education?",
        options: [
          "Technology has only positive effects on education",
          "Technology makes learning unnecessary",
          "Easy access to information may reduce deep thinking",
          "Students should avoid using technology"
        ],
        correctAnswer: "Easy access to information may reduce deep thinking"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 120,
      scoringCriteria: { correctAnswer: "Easy access to information may reduce deep thinking", points: 30 },
      maxScore: 30,
      difficultyWeight: "0.85",
      tags: ["reading", "inference", "critical-thinking"],
      isActive: true,
    },
    {
      skill: "vocabulary",
      cefrLevel: "C1",
      questionType: "multiple_choice",
      title: "Collocations and Idioms",
      prompt: "Choose the correct collocation.",
      content: {
        question: "The company decided to ___ a thorough investigation into the matter.",
        options: ["make", "do", "conduct", "perform"],
        correctAnswer: "conduct"
      },
      responseType: "single_choice",
      expectedDurationSeconds: 45,
      scoringCriteria: { correctAnswer: "conduct", points: 30 },
      maxScore: 30,
      difficultyWeight: "0.80",
      tags: ["vocabulary", "collocations", "advanced"],
      isActive: true,
    },
  ];

  for (const q of questions) {
    await db.insert(placementTestQuestions).values(q);
  }
  console.log(`✅ Seeded ${questions.length} placement test questions across A1-C1 levels.`);
}

export async function seedAllSampleContent() {
  console.log("🌱 Starting sample content seeding...");
  await seedSampleCourses();
  await seedSampleGames();
  await seedPlacementTestQuestions();
  console.log("✅ Sample content seeding complete!");
}
