// ============================================================================
// WORKFLOW STATUS CONSTANTS
// ============================================================================

export const WORKFLOW_STATUS = {
  PENDING: 'pending',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
  ON_HOLD: 'on_hold'
} as const;

export type WorkflowStatus = typeof WORKFLOW_STATUS[keyof typeof WORKFLOW_STATUS];

export const LEAD_STATUS = {
  NEW: 'new',
  CONTACTED: 'contacted',
  QUALIFIED: 'qualified',
  PROPOSAL: 'proposal',
  NEGOTIATION: 'negotiation',
  CLOSED_WON: 'closed_won',
  CLOSED_LOST: 'closed_lost',
  NURTURING: 'nurturing'
} as const;

export type LeadStatus = typeof LEAD_STATUS[keyof typeof LEAD_STATUS];

export const LEAD_WORKFLOW_STAGE = {
  CONTACT_DESK: 'contact_desk',
  NEW_INTAKE: 'new_intake', 
  FOLLOW_UP: 'follow_up',
  NO_RESPONSE: 'no_response',
  LEVEL_ASSESSMENT: 'level_assessment',
  WITHDRAWAL: 'withdrawal',
  NO_SHOW: 'no_show',
  EVALUATION: 'evaluation',
  CONSULTATION_CC: 'consultation_cc',
  CONSULTATION_SUP: 'consultation_sup',
  PRE_REGISTRATION: 'pre_registration',
  FINAL_REGISTRATION: 'final_registration',
  PRIVATE_CLASS_SETUP: 'private_class_setup',
  SET_CLASS_NUMBER: 'set_class_number',
  ACTIVE_PRIVATE_CLASS: 'active_private_class',
  CHARGE_RENEWAL: 'charge_renewal',
  HOLD: 'hold',
  PRIVATE_CLASS_WITHDRAWAL: 'private_class_withdrawal',
  COMPLETED_PRIVATE_CLASS: 'completed_private_class',
  INSTALLMENTS: 'installments',
  CHEQUE: 'cheque',
  ONLINE_ATTENDANCE: 'online_attendance',
  STUDENT_ABSENCE: 'student_absence',
  TEACHER_ABSENCE: 'teacher_absence',
  ENROLLED: 'enrolled'
} as const;

export type LeadWorkflowStage = typeof LEAD_WORKFLOW_STAGE[keyof typeof LEAD_WORKFLOW_STAGE];

export const LEAD_STAGE_TRANSITIONS: Record<LeadWorkflowStage, LeadWorkflowStage[]> = {
  [LEAD_WORKFLOW_STAGE.CONTACT_DESK]: [LEAD_WORKFLOW_STAGE.NEW_INTAKE],
  [LEAD_WORKFLOW_STAGE.NEW_INTAKE]: [LEAD_WORKFLOW_STAGE.FOLLOW_UP, LEAD_WORKFLOW_STAGE.NO_RESPONSE, LEAD_WORKFLOW_STAGE.LEVEL_ASSESSMENT, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.FOLLOW_UP]: [LEAD_WORKFLOW_STAGE.LEVEL_ASSESSMENT, LEAD_WORKFLOW_STAGE.NO_RESPONSE, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.NO_RESPONSE]: [LEAD_WORKFLOW_STAGE.FOLLOW_UP, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.LEVEL_ASSESSMENT]: [LEAD_WORKFLOW_STAGE.EVALUATION, LEAD_WORKFLOW_STAGE.NO_SHOW, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.NO_SHOW]: [LEAD_WORKFLOW_STAGE.FOLLOW_UP, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.EVALUATION]: [LEAD_WORKFLOW_STAGE.CONSULTATION_CC, LEAD_WORKFLOW_STAGE.CONSULTATION_SUP, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.CONSULTATION_CC]: [LEAD_WORKFLOW_STAGE.PRE_REGISTRATION, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.CONSULTATION_SUP]: [LEAD_WORKFLOW_STAGE.PRE_REGISTRATION, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.PRE_REGISTRATION]: [LEAD_WORKFLOW_STAGE.FINAL_REGISTRATION, LEAD_WORKFLOW_STAGE.INSTALLMENTS, LEAD_WORKFLOW_STAGE.CHEQUE, LEAD_WORKFLOW_STAGE.WITHDRAWAL],
  [LEAD_WORKFLOW_STAGE.FINAL_REGISTRATION]: [LEAD_WORKFLOW_STAGE.PRIVATE_CLASS_SETUP, LEAD_WORKFLOW_STAGE.ENROLLED],
  [LEAD_WORKFLOW_STAGE.PRIVATE_CLASS_SETUP]: [LEAD_WORKFLOW_STAGE.SET_CLASS_NUMBER, LEAD_WORKFLOW_STAGE.ACTIVE_PRIVATE_CLASS],
  [LEAD_WORKFLOW_STAGE.SET_CLASS_NUMBER]: [LEAD_WORKFLOW_STAGE.ACTIVE_PRIVATE_CLASS],
  [LEAD_WORKFLOW_STAGE.ACTIVE_PRIVATE_CLASS]: [LEAD_WORKFLOW_STAGE.CHARGE_RENEWAL, LEAD_WORKFLOW_STAGE.HOLD, LEAD_WORKFLOW_STAGE.PRIVATE_CLASS_WITHDRAWAL, LEAD_WORKFLOW_STAGE.COMPLETED_PRIVATE_CLASS, LEAD_WORKFLOW_STAGE.PRIVATE_CLASS_SETUP, LEAD_WORKFLOW_STAGE.ONLINE_ATTENDANCE, LEAD_WORKFLOW_STAGE.STUDENT_ABSENCE, LEAD_WORKFLOW_STAGE.TEACHER_ABSENCE],
  [LEAD_WORKFLOW_STAGE.CHARGE_RENEWAL]: [LEAD_WORKFLOW_STAGE.SET_CLASS_NUMBER],
  [LEAD_WORKFLOW_STAGE.HOLD]: [LEAD_WORKFLOW_STAGE.SET_CLASS_NUMBER],
  [LEAD_WORKFLOW_STAGE.PRIVATE_CLASS_WITHDRAWAL]: [],
  [LEAD_WORKFLOW_STAGE.COMPLETED_PRIVATE_CLASS]: [],
  [LEAD_WORKFLOW_STAGE.INSTALLMENTS]: [LEAD_WORKFLOW_STAGE.FINAL_REGISTRATION],
  [LEAD_WORKFLOW_STAGE.CHEQUE]: [LEAD_WORKFLOW_STAGE.FINAL_REGISTRATION],
  [LEAD_WORKFLOW_STAGE.ONLINE_ATTENDANCE]: [LEAD_WORKFLOW_STAGE.ENROLLED, LEAD_WORKFLOW_STAGE.ACTIVE_PRIVATE_CLASS],
  [LEAD_WORKFLOW_STAGE.STUDENT_ABSENCE]: [LEAD_WORKFLOW_STAGE.ENROLLED, LEAD_WORKFLOW_STAGE.ACTIVE_PRIVATE_CLASS, LEAD_WORKFLOW_STAGE.FOLLOW_UP],
  [LEAD_WORKFLOW_STAGE.TEACHER_ABSENCE]: [LEAD_WORKFLOW_STAGE.ENROLLED, LEAD_WORKFLOW_STAGE.ACTIVE_PRIVATE_CLASS],
  [LEAD_WORKFLOW_STAGE.WITHDRAWAL]: [LEAD_WORKFLOW_STAGE.FOLLOW_UP],
  [LEAD_WORKFLOW_STAGE.ENROLLED]: [LEAD_WORKFLOW_STAGE.ONLINE_ATTENDANCE, LEAD_WORKFLOW_STAGE.STUDENT_ABSENCE, LEAD_WORKFLOW_STAGE.TEACHER_ABSENCE, LEAD_WORKFLOW_STAGE.WITHDRAWAL]
};
